package billingModule;


/**
* billingModule/_BillingImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from billing.idl
* Monday, 7 July, 2025 12:52:33 PM IST
*/

public abstract class _BillingImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements billingModule.Billing, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _BillingImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("generateInvoice", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // billingModule/Billing/generateInvoice
       {
         String itemDetails = in.read_string ();
         String $result = null;
         $result = this.generateInvoice (itemDetails);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:billingModule/Billing:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _BillingImplBase
