package billingModule;


/**
* billingModule/Billing.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from billing.idl
* Monday, 7 July, 2025 12:52:33 PM IST
*/

public interface Billing extends BillingOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Billing
