package billingModule;


/**
* billingModule/BillingOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from billing.idl
* Monday, 7 July, 2025 12:52:33 PM IST
*/

public interface BillingOperations 
{
  String generateInvoice (String itemDetails);
} // interface BillingOperations
