package billingModule;

/**
* billingModule/BillingHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from billing.idl
* Monday, 7 July, 2025 12:52:33 PM IST
*/

public final class BillingHolder implements org.omg.CORBA.portable.Streamable
{
  public billingModule.Billing value = null;

  public BillingHolder ()
  {
  }

  public BillingHolder (billingModule.Billing initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = billingModule.BillingHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    billingModule.BillingHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return billingModule.BillingHelper.type ();
  }

}
